# Generated by Django 3.0.5 on 2020-04-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20200415_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='short_desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
