# Generated by Django 3.0.5 on 2020-04-16 09:04

from django.db import migrations, models
from firstapp.classes.todo import Todo


def populate_new_id(apps, schema_editor):
    """Populate new id field"""

    model = apps.get_model('firstapp', 'Todo')
    queryset = model.objects.all().order_by('date_created')

    for index, todo in enumerate(queryset):
        todo.new_id = index + 1
        todo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20200415_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='new_id',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(populate_new_id),
    ]
