# Generated by Django 3.0.5 on 2020-04-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_todo_new_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='id',
        ),
        migrations.AlterField(
            model_name='todo',
            name='new_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
