# Generated by Django 3.0.5 on 2020-04-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20200416_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='new_id',
            new_name='id',
        ),
    ]
